[package]
name = "goalflow"
edition = "2024.beta"
version = "0.1.0"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
goalflow = "0x0"

[dev-addresses]
goalflow = "0x0"
